#!/bin/bash
# Script to scan audio files and return true peak and various loudness values
# Copyright © 2021 Elizabeth Harmon

# Usage: ebu-scan <input files>.                          

# Check availability of dependencies
function checkAvail()
{
	which "$1" >/dev/null 2>&1
	ret=$?
	if [ $ret -ne 0 ]
	then
		echo "tool \"$1\" not found." >&2
		exit 1
	fi
}

for tool in {ebur128,sox,bc}; \
	do checkAvail "$tool"; done

if [ $# -eq 0 ]
then
	echo "Usage: ebu-scan <input files>"
	exit
fi

# Find real directory name
path=$(realpath "$1")
dirname="${path%/*}"

# Create temp dir and audio files
TEMPDIR=$(mktemp -d)
echo "File|True Peak|Integrated|Short-term|Momentary|LRA" > "$TEMPDIR/tempanalysis"
echo "|(dBTP)|(LUFS)|(LUFS)|(LUFS)|(LU)" >> "$TEMPDIR/tempanalysis"
touch "$TEMPDIR/skipped.txt"

# Count number of arguments
NUMARG=0
NUM=1
SKIPPED=0

# Delete existing analysis.txt if it exists
if [ -f "$dirname/loudness_analysis.txt" ]
then
	rm "$dirname/loudness_analysis.txt"
fi

#Enumerate audio files
for file in "$@"; do
if [ "${file##*.}" == wav ] || [ "${file##*.}" == aif ] || [ "${file##*.}" == aiff ] || [ "${file##*.}" == flac ] || [ "${file##*.}" == ogg ] || [ "${file##*.}" == opus ] || [ "${file##*.}" == mp3 ] || [ "${file##*.}" == wv ];
then
	((NUMARG=NUMARG+1))
fi
done

for file in "$@"; do
# Separate name of file 
FILENAME=${file##*/}

if [ "${file##*.}" == wav ] || [ "${file##*.}" == aif ] || [ "${file##*.}" == aiff ] || [ "${file##*.}" == flac ] || [ "${file##*.}" == ogg ] || [ "${file##*.}" == opus ] || [ "${file##*.}" == mp3 ] || [ "${file##*.}" == wv ];
then
	# Loudness, peak and gain analysis
	ffmpeg -i $file -af ebur128=peak=true -ar 4410 -f null - > "$TEMPDIR/la.txt" 2>&1
	INT=$(awk '/I:   / {print $2}' "$TEMPDIR/la.txt") 
	PEAK=$(awk '/Peak:/ {print $2}' "$TEMPDIR/la.txt") 
	SHORT=$(grep -o 'S: .*' "$TEMPDIR/la.txt" | awk '{print $2}' | sort -rn | head -n 1) 
	MOM=$(grep -o 'M: .*' "$TEMPDIR/la.txt" | awk '{print $2}' | sort -rn | head -n 1)
	LRA=$(awk '/LRA:     / {print $2}' "$TEMPDIR/la.txt")
	echo "$FILENAME|$PEAK|$INT|$SHORT|$MOM|$LRA" >> "$TEMPDIR/tempanalysis"
	echo -ne 'Analyzing...'$NUM'/'$NUMARG'\r'  
	((NUM=NUM+1))

elif [ -f "$file" ]
then
	((SKIPPED=SKIPPED+1))
	echo "$file" >> "$TEMPDIR/skipped.txt"
else
:
fi
done

	#Format analysis data and print	
	echo
	echo	
	cat $TEMPDIR/tempanalysis | column -L -t -s "|" "$TEMPDIR/tempanalysis" | tee "$dirname/loudness_analysis.txt"
	echo
	echo "Skipped files: $SKIPPED"
	cat "$TEMPDIR/skipped.txt"
	printf "\n" >> "$dirname/loudness_analysis.txt"	
	date >> "$dirname/loudness_analysis.txt"

rm -r "$TEMPDIR"
