#!/bin/bash
# Script to scan audio files and return true peak and various loudness values
# Copyright © 2021 Elizabeth Harmon

# Usage: ebu-scan <input files>.                          

if [ $# -eq 0 ]
then
  echo "Usage: ebu-scan <input files>"
  exit
fi

# Find real directory name
path=$(realpath "$1")
dirname="${path%/*}"

# Create temp dir and audio files
TEMPDIR=$(mktemp -d)
echo "Analyzing..."
echo
echo "File|True Peak|Integrated|Short-term|Momentary" > "$TEMPDIR/tempanalysis"
echo "|(dBTP)|(LUFS)|(LUFS)|(LUFS)" >> "$TEMPDIR/tempanalysis"

# Count number of arguments
NUMARG=0
NUM=1

# Delete existing analysis.txt if it exists
if [ -f "$dirname/loudness_analysis.txt" ]
then
  rm "$dirname/loudness_analysis.txt"
fi

#Enumerate audio files
for file in "$@"; do
if [ "${file##*.}" == wav ] || [ "${file##*.}" == aif ] || [ "${file##*.}" == aiff ] || [ "${file##*.}" == flac ] || [ "${file##*.}" == ogg ] || [ "${file##*.}" == opus ];
then
((NUMARG=NUMARG+1))
fi
done

for file in "$@"; do
if [ "${file##*.}" == wav ] || [ "${file##*.}" == aif ] || [ "${file##*.}" == aiff ] || [ "${file##*.}" == flac ] || [ "${file##*.}" == ogg ] || [ "${file##*.}" == opus ];
then
	# Separate name of file 
	FILENAME="$(basename "$file")"

	# Loudness, peak and gain analysis
	ebur128 --full --lufs "$file" > "$TEMPDIR/la.txt"
	INT=$(awk '/loud/ {print $3}' "$TEMPDIR/la.txt") 
	PEAK=$(awk '/Peak/ {print $3}' "$TEMPDIR/la.txt") 
	SHORT=$(awk '/Short/ {print $4}' "$TEMPDIR/la.txt")
	MOM=$(awk '/Mom/ {print $3}' "$TEMPDIR/la.txt")
	echo "$FILENAME|$PEAK|$INT|$SHORT|$MOM" >> "$TEMPDIR/tempanalysis"
	echo -ne $NUM'/'$NUMARG'\r'  
	((NUM=NUM+1))
fi
done

	#Format analysis data and print	
	cat $TEMPDIR/tempanalysis | column -L -t -s "|" "$TEMPDIR/tempanalysis" | tee "$dirname/loudness_analysis.txt"
	echo
	printf "\n" >> "$dirname/loudness_analysis.txt"	
	date >> "$dirname/loudness_analysis.txt"
rm -r "$TEMPDIR"
