#!/bin/bash
# Script to batch normalize files to EBU R 128 (-23 LUFS Integrated)
# Copyright © 2021 Elizabeth Harmon

if [ "$1" = "-t" ] && [ -f "$2" ] 
then
  TARGET=-23
  shift
  echo "No value given after -t flag so using default -23 LUFS"
  sleep 3
elif [ "$1" = "-t" ] 
then
  TARGET=$2
  echo "The target is $TARGET LUFS integrated..."
  shift ; shift
  sleep 3
else
  TARGET=-23
  echo "The target is $TARGET LUFS integrated..."
  sleep 3
fi

path=$(realpath "$1")
dirname="${path%/*}"
mkdir "$dirname/ebu-norm"

TEMPDIR=$(mktemp -d)	
touch "$TEMPDIR"/audioin.$EXT
touch "$TEMPDIR"/audioout.$EXT

for file in "$@";
do
	FILENAME="$(basename "$file")"
	FNAME="${FILENAME%.*}"
	EXT="${file##*.}"
	INT_VALUE=$(ebur128 --lufs "$file" | awk '/Int/ {print $3}')
	GAIN=$(echo $TARGET "-" $INT_VALUE | bc )
  if [ $(echo "$GAIN > 0" | bc) -eq 1 ]
  then 
	LIMITER_LEVEL=$(echo $INT_VALUE "-" $TARGET | bc )
	L3=$(echo $LIMITER_LEVEL "+ -3" | bc ) 
	L2=$(echo $LIMITER_LEVEL "+ -2" | bc ) 
	L1=$(echo $LIMITER_LEVEL "+ -1" | bc ) 
	L0=$(echo $LIMITER_LEVEL "+ 0" | bc ) 
	COMP_1=$(echo "compand 0.005,0.3 1:"$L3","$L3",0,"$L2)
	COMP_2=$(echo "compand 0.002,0.15 1:"$L2","$L2",0,"$L1)
	COMP_3=$(echo "compand 0.001,0.075 1:"$L1","$L1",0,"$L0)
	LIMITER=$(echo "compand 0,0 1:"$L3","$L3",0,"$L0) 

	sox "$file" "$TEMPDIR/audioin.$EXT" $COMP_1
	echo "sox "$file" "$TEMPDIR/audioin.$EXT" $COMP_1"
	sox "$TEMPDIR/audioin.$EXT" "$TEMPDIR/audioout.$EXT" $COMP_2
	sox "$TEMPDIR/audioout.$EXT" "$TEMPDIR/audioin.$EXT" $COMP_3
	sox "$TEMPDIR/audioin.$EXT" "$TEMPDIR/audioout.$EXT" $LIMITER
	sox "$TEMPDIR/audioout.$EXT" "$dirname/ebu-norm/$FNAME-ebu-norm.$EXT" gain $GAIN
  else
	sox "$file" "$dirname/ebu-norm/$FNAME-ebu-norm.$EXT" gain $GAIN
	echo	
	echo $file
	echo "$GAIN dB applied..."
  fi
done

if [ -n "$TEMPDIR" ] 
then
  rm -r "$TEMPDIR"
fi

