#!/bin/bash
# Script to batch normalize files to EBU R 128 (-23 LUFS Integrated)
# Copyright © 2021 Elizabeth Harmon

if [ "$1" = "-t" ] && [ -f "$2" ] 
then
  TARGET=-23
  shift
  echo "No value given after -t flag so using default -23 LUFS"
  sleep 3
elif [ "$1" = "-t" ] 
then
  TARGET=$2
  echo "The target is $TARGET LUFS integrated..."
  shift ; shift
  sleep 3
else
  TARGET=-23
  echo "The target is $TARGET LUFS integrated..."
  sleep 3
fi

path=$(realpath $1)
dirname="${path%/*}"
mkdir "$dirname/Normalized"

for file in "$@";
do
	FILENAME="$(basename "$file")"
	FNAME="${FILENAME%.*}"
	EXT="${file##*.}"
	INT_VALUE=$(ebur128 --lufs "$file" | awk '/Int/ {print $3}')
	GAIN=$(echo $TARGET "-" $INT_VALUE | bc )
	sox "$file" "$dirname/Normalized/$FNAME-normalized.$EXT" gain $GAIN
	echo	
	echo $file
	echo "$GAIN dB applied..."
done
