#!/bin/bash
# Script to batch normalize files to desired true peak value
# Copyright © 2021 Elizabeth Harmon


# Select true peak target based on -t flag or -1 dBTP default
if [ "$1" = "-t" ] && [ -f "$2" ] 
then
  TARGET=-1
  shift
  echo "Please enter a true peak value (0 or lower) if using the -t flag"
  exit
elif [ "$1" = "-t" ] && [ "$2" -gt 0 ]
then
  echo "Please enter a true peak value 0 or lower"
  exit
elif [ "$1" = "-t" ] 
then
  TARGET=$2
  echo "The target is $TARGET dBTP..."
  shift ; shift
  sleep 3
else
  TARGET=-1
  echo "The target is -1 dBTP..."
  sleep 3
fi


# Create subfolder for normalized files
path=$(realpath "$1")
dirname="${path%/*}"
mkdir "$dirname/tp-norm"

for file in "$@";
do
	# Separate name of file 
	FILENAME="$(basename "$file")"
	FNAME="${FILENAME%.*}"
	EXT="${file##*.}"

	# Peak and gain analysis
	PEAK_VALUE=$(ebur128 --lufs --full "$file" | awk '/Peak/ {print $3}')
	GAIN=$(echo $TARGET "-" $PEAK_VALUE | bc )

	# Apply gain
	sox "$file" "$dirname/tp-norm/$FNAME-tp-norm.$EXT" gain $GAIN
	echo	
	echo $file
	echo "$GAIN dB of gain applied..."
done
